name: ta_chovendo_em_joinville
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: Anderson Stühler <anderson@stuhler.com.br>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  angular: ^5.3.0
  angular_components: ^0.13.0
  js: ^0.6.0
  http: ^0.12.0+2

dev_dependencies:
  sass_builder: ^2.1.3
  angular_test: ^2.3.0
  build_runner: ^1.5.0
  build_test: ^0.10.3
  build_web_compilers: ^2.1.0
  pedantic: ^1.8.0
  test: ^1.6.0
